[build]
  publish = "react-website/dist"
  command = "cd react-website && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200